version: '3.8'

services:
  audio-converter:
    image: dncarbonell/ffmpeg-api:v0.1.4
    ports:
      - "8765:8765"
    volumes:
      - ./uploads:/app/uploads
      - ./temp:/app/temp
    environment:
      - NODE_ENV=production
      - PORT=8765
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8765/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s